### PR TITLE
Fix RAML Cop linter after 4.12 upgrade.

### PR DESCRIPTION
**Pull request by distortedsignal**
Small edits.

### CODE REVIEW

**Comment by distortedsignal** [comment]
@braver @thebinarypenguin Not sure what the protocol is for this, but I think that SublimeLinter 4.12 breaks this plugin [as reported in this issue](https://github.com/SublimeLinter/SublimeLinter/issues/1643). Very recently I ran into this difficulty with the SublimeLinter-contrib-erlc plugin and [that plugin ended up getting consumed by the SublimeLinter org](https://github.com/SublimeLinter/SublimeLinter-erlc). Should we do the same thing here?

**Comment by braver** [comment]
If the maintainer doesn’t respond in a timely fashion, we can move it into the org. Let’s give it this weekend, see what happens.

**Comment by distortedsignal** [comment]
@braver I'll ping you next week about this time.

**Comment by distortedsignal** [comment]
@braver ping

**Comment by braver** [comment]
Ok, here we go :)

**Comment by braver** [comment]
@distortedsignal https://github.com/SublimeLinter/SublimeLinter-raml-cop, release is imminent.

**Comment by thebinarypenguin** [comment]
@distortedsignal @braver Hey guys sorry for the slow response I've been busy with a job search (yuck!)

I haven't used RAML or Sublime Text for quite a while so both RAML Cop and the SublimeLinter plugin have been ignored. I'm happy to see it's been absorbed into SublimeLinter org, as I have no desire to continue development.

So how should this transfer of ownership work? Do I need to do anything? Do I need to mark my plugin repo as deprecated and point to the new repo? I'm also willing to transfer ownership or RAML Cop if anyone is interested.

Please advise

**Comment by distortedsignal** [comment]
@thebinarypenguin I don't think _I_ need anything from your end. I've already got the new plugin installed, and it looks like the links in Package Control are either gone or `3xx` to the new package.

I wanted to say thanks for the plugin, and thanks for your work on raml cop. Super cool projects, and they really help me out. Hope your job search is going (has gone?) well, and I hope you find what you're looking for. 😄 

Hope you're having a great day!

**Comment by braver** [comment]
@thebinarypenguin it’s fine as it is. We manage our own section of the package control index, so everything has been moved and updated already. You can put a note in this repo’s readme or archive it. If you ever want to have access to the clone of the repo in the SublimeLinter org, let me know.

**Comment by distortedsignal** [comment]
@braver Thanks again for all your work around SublimeLint and making sure the community feels supported. I think you guys are great!

**Pull request closed without merging**
